### ISSUE TITLE
2.7.5

### ISSUE THREAD

**Issue by Xerus2000** [hypfvieh/dbus-java#10]
I see you are working on a new 3.0 version, which is great :)
but I would appreciate if you would publish a 2.7.5 version to maven, since I am writing a mpris-java library based on this work and encounter the recently fixed issues

**Comment by hypfvieh** [comment]
As you know, there were some fixes/changes recently (one by your own pull request). 
I will not create a new release until a few days/weeks have been passed.

I just want to be sure that the latest changes did not break anything.

Especially the change for using CharSequence instead of String has to be tested very carefully.
Unit tests seem to be happy, but that does not mean everything is fine under all circumstances.

**Comment by Xerus2000** [comment]
I would highly appreciate a pre-release, maybe doing it similar to [logback](https://mvnrepository.com/artifact/ch.qos.logback/logback-classic).

This error message completely ruins debugging right now for me, and it is fixed since #7 
`java.lang.IllegalArgumentException: Cant wrap {0} in an unqualified Variant ({1}).`

**Comment by hypfvieh** [comment]
I don't like what the logback guy is doing. 
Maven central is for releases, not for test or pre-releases. 
All those alpha/beta versions will stay there forever and just pollute the environment.

This remembers me of commons-lang where the maven-versions-plugin will always provide a version 
20030203.000129 (version = timestamp of 2003?!). Or some other artifact I cannot remember the name, which will always provide a 1.X-atlassian1 version, which is also a version created decades ago.

So no, I won't publish unfinished software in maven central.
You are always free to download the sources, compile it yourself and install it to your own local repository (mvn clean install). Then you can build your projects against the SNAPSHOT version and upgrade as soon as the release is done.

**Comment by hypfvieh** [comment]
Dbus-java 2.7.5 is available since 2nd of May 2018. 
Closing this issue
