### ISSUE TITLE
Exporting FileDescriptor

### ISSUE THREAD

**Issue by tincore** [hypfvieh/dbus-java#107]
First of all thanks for the work. This is amazing.
This combined with bluez-dbus is a game changer.

I've been using bluez-dbus successfully with btle devices. I really would like to also use it do classic BT rfcomm and l2cap connections. This could be the best way to use bluetooth devices in java. 

To create a rfcomm connection I need to export a callback (implementation of  org.bluez.Profile1). 

```
[...]
        String profilePath = "/profile/Test";
        dbusConnection.exportObject(profilePath, new ProfileHandler(profilePath));
        ProfileManager profileManager = new ProfileManager(dbusConnection);
        boolean result = profileManager.registerProfile(profilePath, rfCommUuid, profileOptions);
        bluetoothDevice.connectProfile(rfCommUuid.toString());
[...]
```

With the current implementation of the library (3.2.1) I was getting the error:
```
Tried to send message with Unix file descriptorsto a client that doesn't support that.
```

This is similar to what is explained at this recently closed issue: https://github.com/hypfvieh/dbus-java/issues/81

Then I upgraded my dependencies to include <artifactId>dbus-java-nativefd</artifactId>

Now I get this error when calling the exportObject function:
```
org.freedesktop.dbus.exceptions.DBusException: Exporting non-exportable type: class java.io.FileDescriptor
	at org.freedesktop.dbus.Marshalling.recursiveGetDBusType(Marshalling.java:304)
	at org.freedesktop.dbus.Marshalling.getDBusType(Marshalling.java:146)
	at org.freedesktop.dbus.Marshalling.getDBusType(Marshalling.java:131)
	at org.freedesktop.dbus.messages.ExportedObject.getExportedMethods(ExportedObject.java:139)
	at org.freedesktop.dbus.messages.ExportedObject.getExportedMethods(ExportedObject.java:198)
	at org.freedesktop.dbus.messages.ExportedObject.<init>(ExportedObject.java:51)
	at org.freedesktop.dbus.connections.AbstractConnection.exportObject(AbstractConnection.java:312)
```

Do you have any suggestion?

Thanks in advance

**Comment by tincore** [comment]
Epic. One just needs to post a bug to find a solution. 

org.bluez.Profile1 in bluez-dbus

contains 
```
import java.io.FileDescriptor
```
instead of 
```
import org.freedesktop.dbus.FileDescriptor;
```

**Comment by hypfvieh** [comment]
Sorry wrong bugtracker. This is a bug in the current version of bluez-dbus.
I've fixed that and will upload a new version to maven central soon.

**Comment by tincore** [comment]
Sorry for that and thanks again.

Just please be aware that it is possible that bluez-dbus will not be able to achieve the connection with its current dependency on dbus-java. I think that it needs to depend on dbus-java-nativefd.

**Comment by hypfvieh** [comment]
That's true, but it is up to the developer to add dbus-java-nativefd as depenency if needed. 
I will not force anyone to include this optional package because it is only required if you want to use file descriptors.

**Comment by tincore** [comment]
That is very understandable. I was thinking that both bluez-dbus and dbus-java-nativefd depend on dbus-java. There is potential for a dependencies conflict that could be difficult to spot and that could make difficult to explain runtime errors happen.  

I think that this libraries combo is really nice and can be the much needed up to date method for bluetooth java access.

**Comment by hypfvieh** [comment]
dbus-java-nativefd depends on dbus-java because it is an extension for dbus-java.
bluez-dbus depends on dbus-java and only depends on dbus-java-nativefd if filedescriptors are used.

In my eyes, using file descriptors is a very limited use case. Most of the time you can avoid using the technique (there were also discussions to remove support for that kind of stuff from dbus and kernel in general because of possible security issues).

The reason why I don't want to include it, is that dbus-java-nativefd contains native code, which may fail to load on different architectures (e.g. running on ARM instead of x86).

Issue with native libraries, architectures etc. where also the main reason why dbus-java now depends on jnr-unixsocket. Maintaining a library which required native compiled parts is really painful. There are always some people who think you can provide ready-to-use jars for every case. And also trying to be smart to detect architecture and load the proper library is easier said than done. I got a lot of problems with different ARM architectures, so I'm very glad I don't have to mess around with this any longer.

As you may have seen in #81, rm5248 and I tried to add support for file descriptors in dbus-java directly but with the current available jnr-posix implementation it did not work or at least it did not work very reliably. That's why we decide to add support by a third-party library maintained by rm5248.
