### ISSUE TITLE
Add Mac support

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#17]
The current 3.0 tries to open a machine-id file in /var/lib/dbus/machine-id. The dbus daemon on mac (installed with the brew packagemanager - the default) uses /usr/local/var/lib/dbus/machine-id.

The address auto detection for Mac uses only the special Mac env var. Maybe it's good the try the special Mac var first and if not found fall back to the default var.

**Comment by hypfvieh** [comment]
I would prefer to do it the other way around.
I think the more common case is that the library will run on linux, because DBus is always installed and a essential part of the OS.
As you mentioned, Dbus exists for MacOS but if I understand correctly it is not pre-installed or required at all. So I guess, that the usage of dbus + dbus-java on Mac is less common then using dbus + dbus-java on linux systems (most IOT devices use some kind of linux).

**Comment by lbeuster** [comment]
Yes, DBus is an optional package that can be installed via the most used package manager brew. I don't know any real use case under Mac. I only use it for testing our ARM-apps.

**Comment by lbeuster** [comment]
It has been fixed in commit https://github.com/hypfvieh/dbus-java/commit/32442c1572d0b79ff6e5c408cd60eadf5cd6879a#diff-9c6cee1dd7fef7a920b3221627a79c19
