### ISSUE TITLE
Variant memory allocations

### ISSUE THREAD

**Issue by DaveJarvis** [hypfvieh/dbus-java#184]
After resolving #182, instances of `Variant` now dominate memory profiling, as shown in the screenshot:

![Variant](https://user-images.githubusercontent.com/2131950/185474173-caf90411-5df7-4c45-a725-5c32852b274e.png)

The GC profiling shows:

![GC](https://user-images.githubusercontent.com/2131950/185474857-efd459ab-afbf-4abb-9fe9-a5d8e9bba486.png)

Is there anything that can be done to reduce the number of `Variant` instances created? There appears to be a 1:1 relationship with a `Message` instance.

**Comment by hypfvieh** [comment]
That will not be easy to fix (if it is fixable at all).
A Variants array is used in the header of each message ([DBus Spec](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol)) and this header will be read first when a message is transformed to a Java object.

So the same code as for reading anything else on the message is used to get that header information.
This is good in terms of re-using the code, but bad because for the header map in the message only the contents of the variant is stored. Therefore for each messages an arbitrary amount of variants is created, the containing value is stored and the variant itself will be ignored (therefore are eligible for garbage collection).

I'll take a closer look to that, maybe I can refactor some points to get rid of the overhead of creating variant objects.

**Comment by hypfvieh** [comment]
Alright, after hours of investigating, optimizing and refactoring I added a [new branch](https://github.com/hypfvieh/dbus-java/tree/message-variant-improvements) with my changes.

The change will use a new method to read the header for each message which will not create the `Variant` objects.
Instead it will read the data object of the `Variant` directly and return this in the `Object[]` instead of the `Variant`.
Before the change, `Object[]` read from message contained `Byte` + `Variant`, now it contains `Byte` + `Object`.
This allows storing the `Object` directly in the header map (which is `Map<Byte, Object>`) of the message without unwrapping the `Variant` first.

**Comment by DaveJarvis** [comment]
Thank you! The `Variant` instances are now gone:

![dbus-no-variant](https://user-images.githubusercontent.com/2131950/185673808-0a831fcd-2442-4f8d-b57c-0b94430022af.png)

In our application, the `Message` objects promote to Gen 2, which decreases stress on the GC. Decreasing the GC stress reduces the probability of stop-the-world pauses. We have tight timing constraints where stop-the-world events can cause buffer overruns, resulting in dropped data.

Preliminary application tests show significant improvements: there are far fewer stop-the-world events now.
