### ISSUE TITLE
3.0 release timetable

### ISSUE THREAD

**Issue by haggish** [hypfvieh/dbus-java#20]
Hi ! Just a couple of questions.

- Is there any planned release date for version 3.0.0 ?
- Current 3.0.0-SNAPSHOT status - compared to 2.7.5, is it usable already (feature complete / no showstopper bugs / etc.) ?

Cheers

**Comment by hypfvieh** [comment]
Currently there is no schedule for version 3.0.

There are some major changes (especially on internal structures and thread handling), renamed classes/packages etc. 
These changes may cause some issues (e.g. #18 and #19) and even more I'm not aware of yet.

I think version 3.0.0 is usable for testing at least. 
Switching from 2.7.5 to 3.0.0 is not very hard as most of the changes will be fixed by correcting the imported classes.

As soon as #18, #19 and #17 are fixed/done, I will consider to create a release.
But first I'll wait for the initial reports to check if the provided fixes solves the issues they reported.

**Comment by hypfvieh** [comment]
Version 3.0 has just been released.. could take some hours (up to 24) until it is available on maven central.
