### ISSUE TITLE
[Support] Screen recording on Linux (Wayland) using GStreamer and Pipewire... DBUS is really important here...

### ISSUE THREAD

**Issue by sblantipodi** [hypfvieh/dbus-java#224]
Hi,
thank you for making the effort of releasing a Java binding for DBUS...

I would like to record the screen on Linux (wayland) using GStreamer and Pipewire...
This solution seems the best possible on wayland but it heavily requires DBUS...

this is a working snippet of a python program 
https://gitlab.gnome.org/-/snippets/19
that records the screen...

Basically it set up DBus messages to control and acquire the pipewire source to pass into the GStreamer pipeline description.

Are there some examples that can help me understanding how this dbus binding work?

How can I control the pipewire source using this DBUS binding and pass it to GStreamer?

I hope that someone can help here...

I know that issues are not the best way to get help but I think that this can be useful to many people. :)

**Comment by hypfvieh** [comment]
There is no mailing list, forum etc. just this bugtracker - this project is too small for any additional communication platform (and I*m the only maintainer). Therefore it is completely fine to ask questions in the bug tracker.

You are using the wrong bus type and the wrong busname. 
The `org.freedesktop.portal.Desktop` is only visible on the session bus (therefore you have to use `--session` instead of `--system`). Then you also have to specify the correct bus name which is `org.freedesktop.portal.Desktop` and the correct path` /org/freedesktop/portal/desktop` (as seen in d-feet).
Additionally I would add the "--all" flag to create any interface file (you don't know yet which you will need).
 
In the end the command line should look like this:

`mvn exec:java    -Dexec.mainClass="org.freedesktop.dbus.utils.generator.InterfaceCodeGenerator"    -Dexec.executable="java"    -Dexec.args="--all --session --outputDir /tmp/classes org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop"`
