### ISSUE TITLE
Using on MacOS

### ISSUE THREAD

**Issue by nospam2k** [hypfvieh/dbus-java#37]
I saw the Add Mac support was addressed but what is the best way to create a library? I tried running the compile_native.sh and setting target and base dir but it's looking for many libraries. I'd appreciate any help in creating a library.

**Comment by hypfvieh** [comment]
I don't understand the issue...

If there is a suitable binary version for your OS then you can use the binary version of libunix-java which is already part of dbus-java.

In the case you don't want to use the provided binary version or there is no suitable version for you, you have to compile it from source.

Running the 'compile_native.sh' will try to compile the C source code for the libunix-java shared library, which will of course need external libaries/tools/headers as dependencies to be compiled. You have to provide those dependency, otherwise the binary cannot be build.

You need a JDK (at least JDK 1.8), and the Gnu Compiler (GCC, ld) and JAVA_HOME environment variable should be pointing to the JDK 1.8 directory.

**Comment by nospam2k** [comment]
Ok, thx. I can't get it working. I'll use another approach. Thx.
