### ISSUE TITLE
Close Dbus connection withdraw Name from registry

### ISSUE THREAD

**Issue by aygalinc** [hypfvieh/dbus-java#47]
Hi, 

I have the following use case : 
I have describe a systemD dbus service. 
It launches some java app. 
When java app start up is done, i establish Dbus connection and use Dbus object to registre Name. 
When it is done I close the dbus connection because it allocates Thread that will no more be used. As side effect, i see that it withdraw the name from Dbus registry. 

All works perfectly with systemD in version 229. 

I update systemD to version 239 and now the service start but it is immediatly killed. With some test it is clearly link to the Dbus withdraw side effect.

The withdraw is mandatory ? 
Can i stop Dbus connection without the withdraw ?

**Comment by hypfvieh** [comment]
I did not try to use DBus implementation of systemd (I'm not a fan of systemd anyway).
For me it sounds like the described behavior is the expected behavior. 

If you close the DBus connection, usually everything you registered on the bus should be removed.
As DBus is just a type of communication platform, a registered name (end point) without any consumer makes no sense at all (dead end). 

What would you expect to happen if one sends something to your registered object, when you've closed all connections?
I would assume all communication attempts will fail.

What's the problem with the running threads? Threads without any work to do, will cause no harm to anything. They just idle around and will get active if someone is talking to your service.

If you do not want to listen all the time, unregistering and disconnection is the right way to go.

**Comment by aygalinc** [comment]
> What's the problem with the running threads? Threads without any work to do, will cause no harm to anything. They just idle around and will get active if someone is talking to your service.

As stated here https://stackoverflow.com/questions/43795545/is-idle-thread-taking-cpu-execute-time-in-java-executors : 
" threads are a OS resource. So even when they "only exist" and do nothing; they have that "cost". Where again, it might depend on the OS if that could ever turn into a problem " 
In my case, I am on a constraint environment so I get ride of all possible allocated when it is possible. 
Cost can also be related to memory and not only CPU usage. 

Ok for me if it is the desired behavior.

**Comment by hypfvieh** [comment]
if resources are a problem, I would consider using a language which is a bit more memory and CPU friendly than java ... 

Anyway, I'll close this ticket, as there is nothing wrong with dbus-java.
As already stated in [https://github.com/hypfvieh/dbus-java/issues/47#issuecomment-485231961](Comment 2), closing the connection should always removed registered objects from DBus.
