### ISSUE TITLE
Match rules leak when using addSigHandler/removeSigHandler

### ISSUE THREAD

**Issue by littlefreaky** [hypfvieh/dbus-java#76]
In the _DBusConnection_ class, the method _addSigHandler_ (line 875) adds a match rule to the DBus interface by calling _AddMatch_ unconditionally and puts the handler to the internal map used to keep track of the signal handlers. 
The method _removeSigHandler_ (line 779) removes the signal handler from the internal map, but only calls _RemoveMatch_ on the DBus interface if no other handler is in the map which matches the same _SignalTuple_. 

This asymmetry causes a match rule leak when adding and removing multiple signal handlers which result in the same _SignalTuple_ value. 
In my case, the application adds and removes handlers depending on state information. After some time, adding new match rules will fail because the maximum number of allowed rules is reached.

**Comment by hypfvieh** [comment]
I changed the `addSigHandler` (and `addGenericSigHandler`) method to only add the rule to DBus (calling `AddMatch`) if no other signal handler was added with that rule before.

Please test and report back.

**Comment by littlefreaky** [comment]
Thank you very much. I've tested the changes in my environment and can no longer reproduce the exceptions.

**Comment by weliem** [comment]
Great! I was facing the same issue.

Will there be a new release any time soon?

**Comment by hypfvieh** [comment]
I don't think that I'll create a new release in the near future as version 3.2.0 has been released recently and this is the first and only bugfix since release.
I always wait to collect some bug fixes and improvements before creating a release.

My plan is to wait at least until the end of the year or maybe until mid/end of January 2020. 
We will see how many issues will be found and fixed until then.

**Comment by weliem** [comment]
Ok, understandable...no problem
