### ISSUE TITLE
Windows-support?

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#98]
What do you think about Windows support? There's no native dbus but the embedded dbus server works fine. The only issue is the machine id file. If I fake the id (return a hardcoded string as the id) everything works fine.
I could provide a patch but I'm not quite sure if you want to support Windows and how you want to change the machine id stuff for Windows...

**Comment by hypfvieh** [comment]
I don't care about Windows. DBus is for Unix-like systems and was never designed for Windows. 

Also Windows support would be limited, because there is currently no real support for unix sockets (Windows 10 added something like unix sockets, but there are no libraries I'm aware of supporting this feature in java). DBus on TCP should work though, but without features like filedescriptor passing. 
I'm also not sure about the performance. TCP a lot more overhead for protocol handling than a unix socket.

If you want to contribute patches to allow the DbusDaemon to run on windows, please so so.
I cannot test the Windows stuff, because I don't have any Windows system.

**Comment by lbeuster** [comment]
Windows support for us is not meant for production use - only for testing, so file descriptors or performance are not an issue for us. And currently dbus-java already works on Windows with embedded dbus. The only change I had to make is the faked machine id file.
So for us it whould be completely enough to solve this problem somehow, may be in getMachineId():
```
if (Utils.isWindows()) {
    return "hardCodedMachineId";
}
```
If you could live with that simple and ugly solution I provide a patch.

**Comment by hypfvieh** [comment]
Hardcoded does not feel good at all, maybe use the username of the user running the process combinded with machine name or something like that?
